//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackJack.Translations.AppTranslations", typeof(AppTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos.
        /// </summary>
        internal static string aProposToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("aProposToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrière-Plan.
        /// </summary>
        internal static string arrièrePlanToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("arrièrePlanToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleu.
        /// </summary>
        internal static string bleuToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("bleuToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartes.
        /// </summary>
        internal static string cartesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cartesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte.
        /// </summary>
        internal static string carteToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("carteToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couverture.
        /// </summary>
        internal static string couvertureToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("couvertureToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuer.
        /// </summary>
        internal static string distribuerToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("distribuerToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string englishToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("englishToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string françaisToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("françaisToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise : .
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string langueToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("langueToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédits :.
        /// </summary>
        internal static string lblBal_Text {
            get {
                return ResourceManager.GetString("lblBal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueur :.
        /// </summary>
        internal static string lblJoueur_Text {
            get {
                return ResourceManager.GetString("lblJoueur.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino :.
        /// </summary>
        internal static string lblTxCasino_Text {
            get {
                return ResourceManager.GetString("lblTxCasino.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string menuStrip1_Text {
            get {
                return ResourceManager.GetString("menuStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noir.
        /// </summary>
        internal static string noirToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("noirToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle partie.
        /// </summary>
        internal static string nouvellePartieToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("nouvellePartieToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string orangeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("orangeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string paramètresToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("paramètresToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reste.
        /// </summary>
        internal static string resteToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("resteToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouge.
        /// </summary>
        internal static string rougeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("rougeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouge.
        /// </summary>
        internal static string rougeToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("rougeToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lietuvių.
        /// </summary>
        internal static string toolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vert.
        /// </summary>
        internal static string toolStripTextBox1_Text {
            get {
                return ResourceManager.GetString("toolStripTextBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vert.
        /// </summary>
        internal static string vertToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("vertToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string violetToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("violetToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
